create table comment
(
    comment_id            int unsigned auto_increment comment '评论ID'
        primary key,
    comment_article_id    int unsigned                 not null comment '文章ID',
    comment_author_name   varchar(50) charset utf8mb3  null comment '评论人名称',
    comment_author_email  varchar(50) charset utf8mb3  null comment '评论人邮箱',
    comment_author_avatar varchar(100) charset utf8mb3 null comment '评论人头像',
    comment_content       text charset utf8mb3         null comment '内容',
    comment_ip            varchar(50) charset utf8mb3  null comment 'IP',
    comment_create_time   datetime                     null comment '评论时间',
    comment_role          int                          null comment '角色，是否管理员/是否是友人',
    comment_level         int                          null comment '评论等级',
    comment_update_time   datetime                     null comment '更新时间',
    status                int                          null comment '状态',
    is_delete             int                          null comment '是否删除'
)
    row_format = DYNAMIC;

INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (43, 1314, 'unfool', '2935473825@qq.com', null, '很有用处！', '106.122.200.208', '2022-11-15 09:55:54', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (44, 1314, '程序员那些事', '1624374826@qq.com', null, '作者总结的很到位。', '117.30.54.68 ', '2022-11-15 09:55:57', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (45, 1314, '软件匠', '263131625@qq.com', null, '学到了。', '119.180.192.212', '2022-11-17 18:33:11', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (48, 1314, '岁月不如经历', '1426352612@qq.com', null, '我觉得这篇文章很好', '27.223.255.255', '2022-12-07 18:40:14', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (49, 1316, '我就是我', '2863535172@qq.com', null, '计算机专业挺好的，应该是未来趋势。', '211.67.255.255
', '2022-03-25 18:43:40', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (57, 1316, '面包真好吃', '235364324@qq.com', null, '质量很高，感谢作者。', '58.15.255.255
', '2022-12-08 01:31:18', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (58, 1316, '幸福时光', '2234523455@qq.com', null, 'java卷的已经不行了。。。', '117.30.54.68 ', '2022-12-08 03:07:00', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (59, 1316, '博学天空', '1643675327@qq.com', null, '对我帮助很大', '60.235.255.255
', '2022-12-08 03:07:10', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (60, 1316, '牛肉炖土豆', '1635267237@qq.com', null, '赞一个', '119.180.192.212', '2022-12-08 03:07:14', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (61, 1331, '薯片创始人', '27364656361@qq.com', null, '网络安全问题确实要重视。', '150.223.255.255
', '2022-12-08 03:17:10', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (62, 1331, '希望', '2872392768@qq.comwc', null, '这篇文章值得收藏', '180.201.255.255', '2022-12-08 12:19:08', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (63, 1331, '小青草', '1625464253@qq.com', null, '在互联网越来越发达的今天，网络安全问题已不容忽视。', '150.122.255.255', '2022-12-08 12:46:22', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (64, 1331, '星河安全', '2567543355@qq.com', null, '请问还有什么其他的方法吗？', '182.47.255.255
', '2022-12-12 00:29:26', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (65, 1332, 'fish', '2872392768@qq.comwc', null, 'c++很万能，也比较简单。', '203.93.139.255
112.224.0.0', '2022-12-12 12:03:13', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (66, 1332, '开在夏天', '2872392768@qq.com', null, '谢谢作者，已收藏。', '106.122.200.208', '2022-12-13 02:09:10', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (67, 1332, '呱', '2872392768@qq.com', null, 'c++是其他语言的根本。', '211.80.255.255
', '2022-12-13 05:33:31', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (68, 1314, '渺渺兮予怀', '12532323345@qq.com', null, '两种语言都很有用！', '', '2022-12-13 05:40:46', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (70, 1336, '在', '2028524188@stu.htu.edu.cn', null, '<p>肯定还活着呀</p>', null, '2022-12-15 01:28:18', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (72, 1343, '为', '王 ', null, '<p>问问</p>', null, '2022-12-30 03:46:32', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (73, 1337, 'w', '287239s2768@qq.com', null, '<p>we</p>', null, '2023-02-23 01:04:21', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (74, 1386, '强无敌', '2872392768@qq.comwc', null, '<p>按我说的发</p>', null, '2023-03-01 16:45:06', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (75, 1314, '额外v', '2872392768@qq.com', null, '<p>儿童我去饿v</p>', null, '2023-03-02 10:47:49', 0, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (76, 11, 'commentAuthorName', 'commentAuthorEmail', null, 'commentContent', null, null, null, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (77, 11, 'commentAuthorName', 'commentAuthorEmail', null, 'commentContent', null, null, null, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (78, 11, 'commentAuthorName', 'commentAuthorEmail', null, 'commentContent', null, null, null, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (79, 11, 'commentAuthorName', 'commentAuthorEmail', null, 'commentContent', null, null, null, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (80, 11, 'commentAuthorName', 'commentAuthorEmail', null, 'commentContent', null, null, null, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (81, 11, 'commentAuthorName', 'commentAuthorEmail', null, 'commentContent', null, null, null, null, null, null, null);
INSERT INTO yyy.comment (comment_id, comment_article_id, comment_author_name, comment_author_email, comment_author_avatar, comment_content, comment_ip, comment_create_time, comment_role, comment_level, comment_update_time, status, is_delete) VALUES (82, 11, 'commentAuthorName', 'commentAuthorEmail', null, 'commentContent', null, null, null, null, null, null, null);
