spring:
  redis:
    host: 43.143.187.107
    port: 6380
    password: scm13503905942
    database: 0
    jedis:
      pool:
        max-active: 10
        max-wait: 5000
        max-idle: 500
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.143.187.107:3306/yyy?useUnicode=true&characterEncoding=UTF-8&useSSL=false&characterEncoding=UTF8
    username: yyy
    password: scm13503905942
    type: com.alibaba.druid.pool.DruidDataSource
  #配置文件上传
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 30MB
mybatis-plus:
  #  配置外部xml映射
  configuration:
    #    开启SQL日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    开启驼峰映射
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
#JWT配置
jwt:
  header: "Authorization" #token返回头部
  tokenPrefix: "Bearer " #token前缀
  secret: "qwertyuiop7418520" #密钥
  expireTime: 60 #token有效时间 (分钟) 建议一小时以上

#自定义swagger是否启用
swagger:
  enable: true

